language: python
python:
  - 2.7.10
  - 3.5.2
env:
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
install:
  - pip install -r ./todo-project/requirements.txt
  - pip install coveralls
script:
  - coverage run --source=todo-project ./todo-project/manage.py test
after_success:
  coveralls
